### ISSUE TITLE
Query syntax seems wrong

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic_example#8]
https://github.com/zotonic/zotonic_example/blob/fc48d8b1485aa611dc846dddee634c656f64660d/apps/example_site/priv/templates/page.category.tpl#L51
This causes the template rendering to fail in zotonic 1.0.
It works when changing the query to what is described in the documentation
```
       {% with m.search[{ query
                    cat=id
                    sort="-created"
                    pagelen=20
                    page=q.page
                }] as result
        %}
``` 
Similar issue seems to be in the page.website.tpl

**Comment by mworrell** [comment]
Which version of Zotonic are you using?

**Comment by mworrell** [comment]
Good one, it should be:

```django
    {% with m.search.query::%{
            cat: id,
            sort: "-created",
            pagelen: 20,
            page: q.page
        } as result
    %}
```

**Comment by mworrell** [comment]
Should be ok now.

We prefer to use the map syntax going forward, but will keep supporting the property list syntax.

**Comment by karlsson** [comment]
Thanks,
yes it works now. Seems syntax is also relaxed since it works without comma separation.
Just one question about the q.page item, is it safe without escaping?
I just read the [security](https://zotonic.com/cookbook/2325/security-templates-and-xss-prevention) article.
I tried to append the escape filter in the map, but that does not work.

**Comment by mworrell** [comment]
If you echo the `q.page` in your template then you will always need an escape:

```django
{{ q.page|escape }}
```

For the query it is safe to use `q` values directly, they are processed and escaped by the query logic before ending up near the database.

**Comment by karlsson** [comment]
Thanks, Marc.
I feel safe now :-).
